# This workflow will do a clean install of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: wasm-test-runner / pr

on: pull_request

jobs:
  precheck:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout PR
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Use Node.js LTS (16.x)
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run exercism/javascript ci precheck (lint code)
        run: bin/lint.sh

  ci:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout PR
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build the test-runner (using Node ${{ matrix.node-version }})
        run: bin/test.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4
        with:
          install: true

      - name: Build Docker image and store in cache
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          push: false
          load: true
          tags: exercism/wasm-test-runner
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests in Docker
        run: bin/run-tests-in-docker.sh
