name: wasm-test-runner / format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: 'Install pnpm'
        run: npm install -g pnpm
      - name: 'Verify formatting of all files'
        run: ./bin/check-formatting.sh
